# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkmusic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='lyric',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='audio_file',
            field=models.FileField(upload_to='audios/%Y/%m/%d'),
        ),
    ]
