# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 03:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dkmusic', '0002_auto_20170430_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('genre', models.CharField(choices=[('classic', 'Classic'), ('country', 'Country'), ('electronic', 'Electronic'), ('folk', 'Folk'), ('blues', 'Blues'), ('jazz', 'Jazz'), ('pop', 'Pop'), ('R&B', 'R&B'), ('rock', 'Rock'), ('other', 'Other')], default='pop', max_length=200)),
                ('audio_file', models.FileField(upload_to='audios/%Y/%m/%d')),
                ('lyric', models.TextField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='content',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
