# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkmusic', '0004_auto_20170501_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
