# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkmusic', '0006_auto_20170501_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('classic', '经典'), ('country', '乡村'), ('electronic', '电子音乐'), ('folk', '民族'), ('blues', '蓝调'), ('jazz', '爵士'), ('pop', '流行'), ('r_and_b', 'R&B'), ('rock', '摇滚'), ('other', '其他')], default='pop', max_length=200),
        ),
    ]
