# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dkmusic', '0007_auto_20170501_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='user',
        ),
    ]
