# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dkmusic', '0008_auto_20170502_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='songs_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='audio_file',
            field=models.FileField(upload_to='audios/%Y/%m/%d', verbose_name='音乐文件'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('classic', '经典'), ('country', '乡村'), ('electronic', '电子音乐'), ('folk', '民族'), ('blues', '蓝调'), ('jazz', '爵士'), ('pop', '流行'), ('r_and_b', 'R&B'), ('rock', '摇滚'), ('other', '其他')], default='pop', max_length=200, verbose_name='风格'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=200, verbose_name='歌名'),
        ),
    ]
