# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dkmusic', '0009_auto_20170502_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lyric',
        ),
    ]
